language: objective-c
osx_image: xcode7.1
podfile: Podfile

script:
    - xctool -workspace Sightwalk.xcworkspace -scheme Sightwalk -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    - xctool test -workspace Sightwalk.xcworkspace -scheme SightwalkTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

branches:
    only:
        - master
        - develop
